-- get Tn_Transactions_Cube SELECT DISTINCT S.Name [Supplier Name],
	 S.City [Supplier City],
	 S.State [Supplier State],
	 C.Name [Consumer Name],
	 C.City [Consumer City],
	 C.State [Consumer State],
	 P.Name [Product Name],
	 SUM(Quantity) [Total Transactions Quantity],
	 COUNT(Tran_ID) [Number of Transactions]
INTO Tb_Transactions_Cube
 FROM Tb_Supplier S, Tb_Consumer C, Tb_Product P, Tb_Transactions T
 WHERE S.Supp_ID=T.Supp_ID AND
	 C.Con_ID=T.Con_ID AND
	 P.Prod_ID=T.Prod_ID
 GROUP BY CUBE((S.State, S.City, S.Name),
	(C.State, C.City, C.Name),
	P.Name),
	 ROLLUP(S.State, S.City, S.Name),
	 ROLLUP(C.State, C.City, C.Name);--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------1) Aggregates by combinations of supplier name and product name?SELECT tc.[Supplier Name], tc.[Product Name], tc.[Total Transactions Quantity], tc.[Number of Transactions]FROM Tb_Transactions_Cube AS tcWHERE tc.[Consumer Name] IS NULL	AND tc.[Consumer City] IS NULL	AND tc.[Consumer State] IS NULL	AND tc.[Supplier Name] IS NOT NULL	AND tc.[Product Name] IS NOT NULL;--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------2) Aggregates by supplier states?SELECT tc.[Supplier State], tc.[Total Transactions Quantity], tc.[Number of Transactions]FROM Tb_Transactions_Cube AS tcWHERE tc.[Consumer Name] IS NULL	AND tc.[Consumer City] IS NULL	AND tc.[Consumer State] IS NULL	AND tc.[Product Name] IS NULL	AND tc.[Supplier Name] IS NULL	AND tc.[Supplier City] IS NULL	AND tc.[Supplier State] IS NOT NULL;--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------3) Number of transactions between supplier-city-consumer-city pairs?SELECT tc.[Supplier City], tc.[Consumer City], tc.[Total Transactions Quantity], tc.[Number of Transactions]FROM Tb_Transactions_Cube AS tcWHERE tc.[Consumer Name] IS NULL	AND tc.[Consumer City] IS NOT NULL	AND tc.[Consumer State] IS NOT NULL	AND tc.[Product Name] IS NULL	AND tc.[Supplier Name] IS NULL	AND tc.[Supplier City] IS NOT NULL	AND tc.[Supplier State] IS NOT NULL;--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------4) Name of each product and quantity Wisconsin suppliers sold of that
--product?SELECT tc.[Supplier State], tc.[Product Name], tc.[Total Transactions Quantity]FROM Tb_Transactions_Cube AS tcWHERE tc.[Consumer Name] IS NULL	AND tc.[Consumer City] IS NULL	AND tc.[Consumer State] IS NULL	AND tc.[Product Name] IS NOT NULL	AND tc.[Supplier Name] IS NULL	AND tc.[Supplier City] IS NULL	AND tc.[Supplier State] IS NOT NULL	AND tc.[Supplier State] = 'Wisconsin';--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------5) Quantity of sales aggregated by product and supplier state?SELECT tc.[Supplier State], tc.[Product Name], tc.[Total Transactions Quantity]FROM Tb_Transactions_Cube AS tcWHERE tc.[Consumer Name] IS NULL	AND tc.[Consumer City] IS NULL	AND tc.[Consumer State] IS NULL	AND tc.[Product Name] IS NOT NULL	AND tc.[Supplier Name] IS NULL	AND tc.[Supplier City] IS NULL	AND tc.[Supplier State] IS NOT NULL;--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------6) Quantity of computer sales aggregated by suppliers in Wisconsin?SELECT tc.[Supplier State], tc.[Product Name], tc.[Total Transactions Quantity]FROM Tb_Transactions_Cube AS tcWHERE tc.[Consumer Name] IS NULL	AND tc.[Consumer City] IS NULL	AND tc.[Consumer State] IS NULL	AND tc.[Product Name] IS NOT NULL	AND tc.[Supplier Name] IS NULL	AND tc.[Supplier City] IS NULL	AND tc.[Supplier State] IS NOT NULL	AND tc.[Supplier State] = 'Wisconsin'	AND tc.[Product Name] = 'Computer';--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------7) Quantity of auto sales by each supplier from Wisconsin to each auto
--consumer in Illinois?-- get quantity_auto_from_s_wisconsin_to_c_illinoisSELECT tc.[Supplier Name], tc.[Supplier City], tc.[Supplier State], 	tc.[Consumer Name], tc.[Consumer City], tc.[Consumer State],	tc.[Product Name], tc.[Total Transactions Quantity]INTO #quantity_auto_from_s_wisconsin_to_c_illinoisFROM Tb_Transactions_Cube AS tcWHERE tc.[Consumer Name] IS NOT NULL	AND tc.[Consumer City] IS NOT NULL	AND tc.[Consumer State] IS NOT NULL	AND tc.[Product Name] IS NOT NULL	AND tc.[Supplier Name] IS NOT NULL	AND tc.[Supplier City] IS NOT NULL	AND tc.[Supplier State] IS NOT NULL	AND tc.[Supplier State] = 'Wisconsin'	AND tc.[Consumer State] = 'Illinois'	AND tc.[Product Name] = 'Auto';--SELECT *--FROM #quantity_auto_from_s_wisconsin_to_c_illinois-- get auto_c_illinoisSELECT DISTINCT tc.[Consumer Name], tc.[Product Name]INTO #auto_c_illinoisFROM Tb_Transactions_Cube AS tcWHERE tc.[Consumer State] = 'Illinois'	AND tc.[Product Name] = 'Auto'	AND tc.[Consumer Name] IS NOT NULL;--SELECT *--FROM #auto_c_illinois-- get quantity of auto sales by each wisconsin supplier to illinois auto consumersSELECT tc.[Supplier Name], tc.[Supplier City], tc.[Supplier State], 	tc.[Consumer Name], tc.[Consumer City], tc.[Consumer State],	tc.[Product Name], auto.[Total Transactions Quantity]FROM Tb_Transactions_Cube AS tc	LEFT JOIN #quantity_auto_from_s_wisconsin_to_c_illinois AS auto		ON tc.[Supplier Name] = auto.[Supplier Name] 			AND tc.[Supplier City] = auto.[Supplier City]			AND tc.[Supplier State] = auto.[Supplier State] 			AND tc.[Consumer Name] = auto.[Consumer Name] 			AND tc.[Consumer City] = auto.[Consumer City]			AND tc.[Consumer State] = auto.[Consumer State]			AND tc.[Product Name] = auto.[Product Name]	RIGHT JOIN #auto_c_illinois AS auto_c		ON tc.[Consumer Name] = auto_c.[Consumer Name]			AND tc.[Product Name] = auto_c.[Product Name]WHERE tc.[Consumer Name] IS NOT NULL	AND tc.[Consumer City] IS NOT NULL	AND tc.[Consumer State] IS NOT NULL	AND tc.[Product Name] IS NOT NULL	AND tc.[Supplier Name] IS NOT NULL	AND tc.[Supplier City] IS NOT NULL	AND tc.[Supplier State] IS NOT NULL	AND tc.[Supplier State] = 'Wisconsin'	AND tc.[Consumer State] = 'Illinois';DROP TABLE #quantity_auto_from_s_wisconsin_to_c_illinois;DROP TABLE #auto_c_illinois;--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------8) Quantity of each product sold by each supplier in Madison to each
--consumer in Illinois?SELECT tc.[Supplier Name], tc.[Supplier City], tc.[Product Name], tc.[Consumer Name], tc.[Consumer State],	tc.[Total Transactions Quantity]FROM Tb_Transactions_Cube AS tcWHERE tc.[Consumer Name] IS NOT NULL	AND tc.[Consumer City] IS NOT NULL	AND tc.[Consumer State] IS NOT NULL	AND tc.[Product Name] IS NOT NULL	AND tc.[Supplier Name] IS NOT NULL	AND tc.[Supplier City] IS NOT NULL	AND tc.[Supplier State] IS NOT NULL	AND tc.[Supplier City] = 'Madison'	AND tc.[Consumer State] = 'Illinois';--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------9) Quantity of each product sold by supplier Bernstein to consumers in
--Chicago?SELECT tc.[Supplier Name], tc.[Product Name], tc.[Consumer City], tc.[Total Transactions Quantity]FROM Tb_Transactions_Cube AS tcWHERE tc.[Consumer Name] IS NULL	AND tc.[Consumer City] IS NOT NULL	AND tc.[Consumer State] IS NOT NULL	AND tc.[Product Name] IS NOT NULL	AND tc.[Supplier Name] IS NOT NULL	AND tc.[Supplier City] IS NOT NULL	AND tc.[Supplier State] IS NOT NULL	AND tc.[Supplier Name] = 'Bernstein'	AND tc.[Consumer City] = 'Chicago';--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------10) Quantity of milk sold by supplier Bernstein to each of his milk
--consumers in Chicago?SELECT tc.[Supplier Name], tc.[Product Name], tc.[Consumer Name], tc.[Consumer City], tc.[Total Transactions Quantity]FROM Tb_Transactions_Cube AS tcWHERE tc.[Consumer Name] IS NOT NULL	AND tc.[Consumer City] IS NOT NULL	AND tc.[Consumer State] IS NOT NULL	AND tc.[Product Name] IS NOT NULL	AND tc.[Supplier Name] IS NOT NULL	AND tc.[Supplier City] IS NOT NULL	AND tc.[Supplier State] IS NOT NULL	AND tc.[Supplier Name] = 'Bernstein'	AND tc.[Consumer City] = 'Chicago'	AND tc.[Product Name] = 'Milk';--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------11) (Extra Credit 2%) For each product list quantity sold by suppliers in
--Madison to consumers in Chicago versus quantity sold by suppliers in
--Chicago to consumers in Madison (result columns will be: product name,
--quantity Madison_Chicago, quantity Chicago_Madison)?-- get q_madison_chicagoSELECT tc.[Supplier City], tc.[Product Name], tc.[Consumer City], 	tc.[Total Transactions Quantity] AS quantity_madison_chicagoINTO #q_madison_chicagoFROM Tb_Transactions_Cube AS tcWHERE tc.[Consumer Name] IS NULL	AND tc.[Consumer City] IS NOT NULL	AND tc.[Consumer State] IS NOT NULL	AND tc.[Product Name] IS NOT NULL	AND tc.[Supplier Name] IS NULL	AND tc.[Supplier City] IS NOT NULL	AND tc.[Supplier State] IS NOT NULL	AND tc.[Supplier City] = 'Madison'	AND tc.[Consumer City] = 'Chicago';--SELECT *--FROM #q_madison_chicago-- get q_chicago_madisonSELECT tc.[Supplier City], tc.[Product Name], tc.[Consumer City], 	tc.[Total Transactions Quantity] AS quantity_chicago_madisonINTO #q_chicago_madisonFROM Tb_Transactions_Cube AS tcWHERE tc.[Consumer Name] IS NULL	AND tc.[Consumer City] IS NOT NULL	AND tc.[Consumer State] IS NOT NULL	AND tc.[Product Name] IS NOT NULL	AND tc.[Supplier Name] IS NULL	AND tc.[Supplier City] IS NOT NULL	AND tc.[Supplier State] IS NOT NULL	AND tc.[Supplier City] = 'Chicago'	AND tc.[Consumer City] = 'Madison';--SELECT *--FROM #q_chicago_madison-- join q_madison_chicago and q_chicago_madison to list of all productsSELECT tc.[Product Name], 	ISNULL(qmc.quantity_madison_chicago, 0), 	ISNULL(qcm.quantity_chicago_madison, 0)FROM (SELECT DISTINCT tc.[Product Name]		FROM Tb_Transactions_Cube AS tc		WHERE tc.[Product Name] IS NOT NULL) AS tc	LEFT JOIN #q_madison_chicago AS qmc		ON tc.[Product Name] = qmc.[Product Name]	LEFT JOIN #q_chicago_madison AS qcm		ON tc.[Product Name] = qcm.[Product Name];DROP TABLE #q_chicago_madison;DROP TABLE #q_madison_chicago;	------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------